pipeline

diff --git a/.github/workflows/cd-pipeline.yml b/.github/workflows/cd-pipeline.yml
--- a/.github/workflows/cd-pipeline.yml
+++ b/.github/workflows/cd-pipeline.yml
@@ -100,43 +100,40 @@ jobs:
 
       - name: Login to ArgoCD
         run: |
-          argocd login localhost:8080 \ --username admin \
-          --password V9WseQDEtlR4TJCh \ --insecure
+          argocd login $ARGOCD_SERVER \
+            --username $ARGOCD_USERNAME \
+            --password $ARGOCD_PASSWORD \
+            --insecure
 
-      # - name: Login to ArgoCD
-      #   run: |
-      #     argocd login $ARGOCD_SERVER --username $ARGOCD_USERNAME --password $ARGOCD_PASSWORD --insecure
+      - name: Validar políticas de despliegue
+        run: |
+          if [[ "${GITHUB_REF}" == "refs/heads/test" ]]; then
+            app_name="microservices-test"
+          elif [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
+            app_name="microservices-prod"
+          else
+            echo "Rama no soportada"
+            exit 1
+          fi
 
-      # - name: Validar políticas de despliegue
-      #   run: |
-      #     if [[ "${GITHUB_REF}" == "refs/heads/test" ]]; then
-      #       app_name="microservices-test"
-      #     elif [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
-      #       app_name="microservices-prod"
-      #     else
-      #       echo "Rama no soportada"
-      #       exit 1
-      #     fi
+          estado=$(argocd app get $app_name -o json | jq -r '.status.health.status')
+          sync=$(argocd app get $app_name -o json | jq -r '.status.sync.status')
 
-      #     estado=$(argocd app get $app_name -o json | jq -r '.status.health.status')
-      #     sync=$(argocd app get $app_name -o json | jq -r '.status.sync.status')
+          if [[ "$estado" != "Healthy" || "$sync" != "Synced" ]]; then
+            echo "❌ Error: La aplicación $app_name no está saludable o sincronizada"
+            exit 1
+          fi
 
-      #     if [[ "$estado" != "Healthy" || "$sync" != "Synced" ]]; then
-      #      echo "❌ Error: La aplicación $app_name no está saludable o sincronizada"
-      #       exit 1
-      #     fi
+      - name: Desplegar según la rama
+        run: |
+          if [[ "${GITHUB_REF}" == "refs/heads/test" ]]; then
+            app_name="microservices-test"
+          elif [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
+            app_name="microservices-prod"
+          fi
 
-      # - name: Desplegar según la rama
-      #   run: |
-      #     if [[ "${GITHUB_REF}" == "refs/heads/test" ]]; then
-      #       app_name="microservices-test"
-      #     elif [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
-      #       app_name="microservices-prod"
-      #     fi
-
-      #     argocd app sync $app_name
-      #     argocd app wait $app_name --timeout 300
-      #
+          argocd app sync $app_name
+          argocd app wait $app_name --timeout 300
 
       - name: Enviar notificación por WhatsApp
         run: |
